### ISSUE TITLE
"msg":"failure in decrypting message"} 

### ISSUE THREAD

**Issue by mateuscdor** [Dakauann/trashdkbot-md-public#1]
Node.js v16.13.0
MD: TRUE
SOCKET: SIM
----------------------------------------------

"msg":"failure in decrypting message"}
ATUALIZAÇÃO DE CONEXÃO:  { receivedPendingNotifications: true }

Não é possivel ler a mensagem criptografada.

não foi alterado nada no código.

**Comment by Dakauann** [comment]
Caso você fique muito tempo sem abrir a sessão, a md terá que recarregar todas as mensagens, não se preocupe pois futuramente atualizarei este repositório com os novos sistemas de login adotados pela api.
